### ISSUE TITLE
Expose `zcash_client_backend::data_api::WalletRead::get_wallet_summary` via the FFI

### ISSUE THREAD

**Issue by nuttycom** [Electric-Coin-Company/zcash-light-client-ffi#101]
Partial wallet summary information is currently available for balance queries, but we also need to expose at a minimum the list of accounts in the wallet, and if possible a more complete representation of the summary data.

**Comment by str4d** [comment]
This would also likely fix a performance issue, because we can replace three FFI calls (for total and available balance, and scan progress) with a single FFI call (for the wallet summary). The equivalent Android issue is https://github.com/zcash/zcash-android-wallet-sdk/issues/1282.
