### ISSUE TITLE
TestFlight - The Info.plist file is missing the required key: CFBundleShortVersionString

### ISSUE THREAD

**Issue by pacu** [Electric-Coin-Company/zcash-light-client-ffi#144]
Unstoppable is having issues uploading  to TestFlight because of the following error:

*** Error: Asset validation failed The bundle 'Payload/Unstoppable.app/Frameworks/libzcashlc.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring (ID: 62d555af-4a1b-453c-b572-e6a14ecf4a55) (90057)

Seems like Zcash library is missing some plist keys.

**Comment by LukasKorba** [comment]
Fixed in SDK [2.1.10](https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/releases/tag/2.1.10)
