### ISSUE TITLE
libzcashlc was built for newer 'iOS' version (17.5) than being linked (15.0)

### ISSUE THREAD

**Issue by pacu** [Electric-Coin-Company/zcash-light-client-ffi#153]
When building the swift sdk 2.2.3 

Unstoppable reported this issue 

```
object file (.../libzcashlc.framework/libzcashlc[arm64][3](d1fba762150c532c-wrapper.o)) was built for newer 'iOS' version (17.5) than being linked (15.0)

```

Seems like libzcashlc.framework was built for min target of 17.5.

**Comment by str4d** [comment]
We're now building release binaries with the much older Xcode 13 (on an old laptop that @nuttycom has).

We've also added a CI workflow for the preview builds that also currently uses Xcode 13, but will be forced to migrate to Xcode 14 in December (as GitHub is dropping the `macos-12` runner, and `macos-13` requires a minimum of Xcode 14).

@pacu please confirm that this issue does not occur with Swift SDK 2.2.7 (being released today).

**Comment by pacu** [comment]
oops, I was notification swamped. I apologized for not seeing this. guys you can always ping me, you know 🫶

**Comment by pacu** [comment]
I can't reproduce the problem on commit `c9fb3485a6c427080d2ed63c1e2ba464ecaee52c`
